[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
open_dialogue_dapp = "7YYvcE2oVjBGvFEyt4q3Ye6knDw2wE4j7Xi2tji9oNSW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"

[test.validator]
rpc_port = 8899
bind_address = "localhost"
startup_wait = 10000
ledger = ".anchor/test-ledger"
clone = [
  { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" }  # Metadata program
]